services:
  - type: web
    name: programa-21-dias
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server.cjs
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/programs
